version: '3.8'

services:

  badge-pg:
    image: postgres:14
    container_name: badge-pg
    restart: unless-stopped
    env_file: .db.env
    ports:
      - '9002:5432'
    volumes:
      - database-data:/var/lib/postgresql-docker/data/

volumes:
  database-data: null